<template>
    <div
        :class="[
            'cover' + $store.state.cover,
            'slide',
            'ending',
            'page',
            'page18',
            'about'
        ]"
    >
        <div class="overlay">
            <div @click="$emit('changePage', 17)" class="close">
                &#10005;
            </div>
            <div class="body">
                <div class="paragraph">
                   Eat-Project is the first network channel with the
                        ambition to connect two worlds:
                        <span>Gastronomy & Digital Health</span>
                </div>
                <div class="paragraph">
                    2007 was a year of a particular stir around many fashion
                        companies on an international level. Many of these were
                        strongly criticized by public opinion regarding the
                        <span>"physical condition" of the young models</span>
                        they collaborate with. In the same year some of them
                        decided to start <span>nutritional projects</span> with
                        the specific goal of educating those teenage on the
                        right way to preserve physical shape without neglecting
                        health, through the proper nutritional plan
                        supported by health. However, in order to be able to
                        achive the right strategy based
                       on  <span>quality and wide variety,</span>
                        they needed a fundamental ingredient: <span>data.</span>
                </div>
                <div class="paragraph">
                       It’s 2007, and the digital gastronomy web channels were
                        at the beginning. The team was made up of two
                        programmers, who started mapping thousands of recipes
                        with their respective nutrients. After the end of the
                        project in 2012, the team decided to offer their
                        data-know-how to freelance dieticians and nutritionists,
                        reaching out
                        <span
                            >a network of over 5,000 experts from Italy, Brazil,
                            and USA, and</span>   <span>“connecting people to diet professionals”</span>                       
                            via WhatsApp and e-mail. <br>After 12 years of collaboration, in 2020 the two
                        Co-Founders decide to work on the
                        <span>first MVP version of Eat-Project.</span>
                </div>

                

                <div class="paragraph">
                    Nowadays, the topic of information certification has
                        become increasingly controversial and a source of huge
                        discussion. A lack of information’s reliability has been
                        generated by the abuse of digital tools that allow the
                        creation and dissemination of information without any
                        scientific basis. And as often happens, such speculation
                        also involves health industry.
                </div>

                <div class="paragraph">
                     The only way to be able to guarantee users a high level
                        of information's reliability on the network, is to
                       
                              <span>promote new channels</span > designed to limiting the
                            dissemination of<br>  <span>"fake information".</span >
                </div>

                <div class="paragraph">
                    The project was born to meet the needs of who must 
                        find
                        a compromise between <span>gastronomic preferences</span>
                            and <span>nutritional needs</span>, either <span>“Home &
                            On-The-Go”.</span>
                </div>

                <div class="paragraph">
                    But Eat-Project doesn't want to be just nutritional
                        information.<br> The project is a network for
                        millions of users looking for gastronomic inspiration
                        through the collaboration of many other professionals in
                        the Food industry (<span
                            >Chef, Food Bloggers, Food photographers, Food
                            Reporters, sommeliers, Bar Tenders, Food Companies,
                             etc...</span
                        >). <br>Together they will be able to work in the creation,
                        enhancement, and sharing of multimedia content with a
                        high creative and information value.
                </div>

                <div class="paragraph">
                    The company chooses <span>Milan</span> for strategic reasons related
                        to the gastronomic and food environment. <br>Also called
                        <span>"food valley"</span>, after EXPO 2015 Milan
                        becomes the first global reference center for the food
                        industry, with over 400 events per year, sposored by 3,080 Italian and foreign 
                       brands, over 82,000 visitors
                        and 2, 2 billion in revenues.
                </div>
            </div>
            <div class="footer">Copyright © 2020, Eat-Project</div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'About',
    data() {
        return {
            startAnimation: false
        };
    },
    props: {
        animate: {
            type: Boolean,
            default: false,
            required: false
        }
    },
    watch: {
        animate(val) {
            if (val == true) {
                this.startAnimation = true;
                this.$emit('stopAnimation');
            }
        }
    },
    mounted() {
        //in case the slide is loaded with a direct link
        if (this.animate == true) {
            this.startAnimation = true;
            this.$emit('stopAnimation');
        }
    },
    created() {
        this.$store.commit('updateCurrentPage', 18);
    }
};
</script>

<style lang="scss" scoped>
.about {
    .overlay {
        .body {
            max-height: 70vh;
            font-size: 2.3rem;

            word-break: keep-all;

            overflow-y: scroll;

            .paragraph {
                &:not(:last-child) {
                    margin-bottom: 2rem;
                }

                span {
                    font-weight: 700;
                }
            }
        }
    }
}
</style>
